### ISSUE TITLE
Error importing module on Windows 7

### ISSUE THREAD

**Issue by gruden-g2** [Actifio/powershell#3]
64-bit Windows 7, Professional Edition.  With powershell v. 3 and .Net 4.5, I get error attempting to load the Actifio Powershell module:
Import-Module : Could not load file or assembly
'file:///C:\Windows\system32\WindowsPowerShell\v1.0\Modules\ActPowerCLI\ActPowerCLI.dll' or one of its dependencies.
Operation is not supported. (Exception from HRESULT: 0x80131515)
At line:1 char:1
+ Import-Module ActPowerCLI
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : FormatXmlUpdateException,Microsoft.PowerShell.Commands.ImportModuleCommand

Upgraded to Powershell 5.1, same error.  This works fine on a Windows 2012 R2 server.

**Comment by aussiestorblog** [comment]
Did you do the following?

Delete the actpowercli folder in c:\windows\system32\windowspowershell\v1.0\modules or where ever you placed it
Right select the downloaded zip file and choose properties
At the bottom of the properties window select the Unblock button next to the message: This file came from another computer and might be blocked to help protect this computer
Unzip and again copy the folder into c:\windows\system32\windowspowershell\v1.0\modules or which ever path you are using

**Comment by gruden-g2** [comment]
I saw that in your docs but it described a different error so I didn't try that, but that definitely applied here. Maybe you could add the error I reported as a possible symptom for this fix.  I also found that your module has to be added to the \program files (x86) path for powershell in order for your module to work in the 32-bit powershell console in addition, maybe that could be added as well.  Thanks for your help.

**Comment by aussiestorblog** [comment]
Will definately update the docs based on your experience.   Thanks for your help!

**Comment by aussiestorblog** [comment]
I updated the readme and the FAQ Document
